/*
Navicat MySQL Data Transfer

Source Server         : localhost_3306
Source Server Version : 50527
Source Host           : localhost:3306
Source Database       : housingdb

Target Server Type    : MYSQL
Target Server Version : 50527
File Encoding         : 65001

Date: 2017-12-06 09:27:46
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `tb_choose1`
-- ----------------------------
DROP TABLE IF EXISTS `tb_choose1`;
CREATE TABLE `tb_choose1` (
  `id` varchar(10) NOT NULL,
  `isSelected` tinyint(4) DEFAULT NULL,
  `person_id` varchar(10) DEFAULT NULL,
  `p0_name` varchar(10) DEFAULT NULL,
  `select_seq` varchar(20) DEFAULT NULL,
  `select_time` varchar(30) DEFAULT NULL,
  `remark` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of tb_choose1
-- ----------------------------
INSERT INTO `tb_choose1` VALUES ('1', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('10', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('100', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('101', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('102', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('103', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('104', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('105', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('106', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('107', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('108', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('109', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('11', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('110', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('111', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('112', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('113', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('114', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('115', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('116', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('117', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('118', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('119', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('12', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('120', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('121', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('122', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('123', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('124', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('125', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('126', '1', '2100', '曹杨', '1', '2017-11-21 17:49:28', '');
INSERT INTO `tb_choose1` VALUES ('127', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('128', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('129', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('13', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('130', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('131', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('132', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('133', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('134', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('135', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('136', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('137', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('138', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('139', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('14', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('140', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('141', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('142', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('143', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('144', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('145', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('146', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('147', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('148', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('149', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('15', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('150', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('151', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('152', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('153', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('154', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('155', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('156', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('157', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('158', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('159', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('16', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('160', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('161', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('162', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('163', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('164', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('165', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('166', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('167', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('168', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('169', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('17', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('170', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('171', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('172', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('173', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('174', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('175', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('176', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('177', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('178', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('179', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('18', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('180', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('181', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('182', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('183', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('184', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('185', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('186', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('187', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('188', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('189', '1', '2102', '关继伟', '3', '2017-11-23 20:55:32', '');
INSERT INTO `tb_choose1` VALUES ('19', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('190', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('191', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('192', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('193', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('194', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('195', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('196', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('197', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('198', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('199', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('2', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('20', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('200', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('201', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('202', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('203', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('204', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('205', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('206', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('207', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('208', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('209', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('21', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('210', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('211', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('212', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('213', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('214', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('215', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('216', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('217', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('218', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('219', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('22', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('220', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('221', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('222', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('223', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('224', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('225', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('226', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('227', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('228', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('229', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('23', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('230', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('231', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('232', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('233', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('234', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('235', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('236', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('237', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('238', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('239', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('24', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('240', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('241', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('242', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('243', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('244', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('245', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('246', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('247', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('248', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('249', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('25', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('250', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('251', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('252', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('253', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('254', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('255', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('256', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('257', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('258', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('259', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('26', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('260', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('261', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('262', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('263', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('264', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('265', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('266', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('267', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('268', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('269', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('27', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('270', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('271', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('272', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('273', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('274', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('275', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('276', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('277', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('278', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('279', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('28', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('280', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('281', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('282', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('283', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('284', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('285', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('286', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('287', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('288', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('289', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('29', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('290', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('291', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('292', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('293', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('294', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('295', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('296', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('297', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('298', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('299', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('3', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('30', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('300', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('301', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('302', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('303', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('304', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('305', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('306', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('307', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('308', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('309', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('31', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('310', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('311', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('312', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('313', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('314', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('315', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('316', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('32', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('33', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('34', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('35', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('36', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('37', '1', '2106', '侯景辉', '2', '2017-11-21 17:56:36', '');
INSERT INTO `tb_choose1` VALUES ('38', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('39', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('4', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('40', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('41', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('42', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('43', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('44', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('45', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('46', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('47', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('48', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('49', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('5', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('50', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('51', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('52', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('53', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('54', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('55', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('56', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('57', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('58', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('59', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('6', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('60', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('61', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('62', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('63', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('64', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('65', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('66', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('67', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('68', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('69', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('7', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('70', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('71', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('72', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('73', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('74', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('75', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('76', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('77', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('78', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('79', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('8', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('80', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('81', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('82', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('83', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('84', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('85', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('86', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('87', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('88', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('89', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('9', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('90', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('91', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('92', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('93', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('94', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('95', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('96', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('97', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('98', '0', '', '', '0', '', '');
INSERT INTO `tb_choose1` VALUES ('99', '0', '', '', '0', '', '');
